version: "2"
services:
  identifier:
    image: semtech/mu-identifier:1.3.0
    links:
      - dispatcher:dispatcher
    ports:
      - "8011:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  as:
    # build: ~/code/mu-graph-rewriter
    image: nathanielrb/mu-graph-rewriter:0.6.0
    links:
      - db:database
    environment:
      MU_DEFAULT_GRAPH: "http://mu.semte.ch/application" # probably unused 
      PLUGIN_PATH: "/config/school-access-triples.scm"
      MESSAGE_LOGGING: "true"
      PRINT_SPARQL_QUERIES: "true"
      USE_TEMP: "false"
      CALCULATE_POTENTIALS: "true"
      REWRITE_SELECT_QUERIES: "true"
    volumes:
      - ./config/rewriter:/config
    ports:
      - "4005:4005"
      - "4027:8890"
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.15.0
    links:
      - as:database
    volumes:
      - ./config/resources:/config
    ports:
      - "4444:80"
