version: "2"
services:
  sandbox:
    image: semtech/ember-proxy-service
    ports:
      - "9000:80"
    links:
      - identifier:backend
    volumes:
      - ./sandbox:/app
  identifier:
    image: semtech/mu-identifier:1.3.0
    links:
      - dispatcher:dispatcher
    ports:
      - "8011:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    links:
      - resource:resource
      - as:as
    volumes:
      - ./config/dispatcher:/config
    ports:
      - "4028:80"
  as:
    image: nathanielrb/mu-graph-rewriter:0.8.0
    links:
      - db:database
    environment:
      MU_DEFAULT_GRAPH: "http://mu.semte.ch/application" # probably unused 
      MESSAGE_LOGGING: "true"
      PRINT_SPARQL_QUERIES: "true"
      USE_TEMP: "false"
      CALCULATE_POTENTIALS: "true"
      REWRITE_SELECT_QUERIES: "true"
    volumes:
      - ./config/rewriter:/config
      - ~/code/mu-graph-rewriter/sandbox:/app/sandbox
    ports:
      - "4005:4005"
      - "4027:8890"
  generator:
    build: ./random-data-generator
    links:
      - as:database
    volumes:
      - ./random-data-generator:/app
    ports:
      - "4030:80"
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.15.0
    links:
      - as:database
    volumes:
      - ./config/resources:/config
    ports:
      - "4444:80"
